=== mayank341/MyPractice/HTML-WebTec/student.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name, email, phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

<!ATTLIST student id CDATA #REQUIRED>














<!-- // implied-- optional 
// anmTOKENS -----MULtiple values . -->

=== mayank341/MyPractice/HTML-WebTec/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "student.dtd">

<students>
    <student id="101">
        <name>Rahul Sharma</name>
        <email>rahul.sharma@example.com</email>
        <phone>9876543210</phone>
    </student>

    <student id="102">
        <name>Anjali Verma</name>
        <email>anjali.verma@example.com</email>
        <phone>9123456780</phone>
    </student>

    <student id="103">
        <name>Arjun Kumar</name>
        <email>arjun.kumar@example.com</email>
        <phone>9988776655</phone>
    </student>
</students>
